### ISSUE TITLE
Able to extends presets and plugins

### ISSUE THREAD

**Issue by faizshukri** [holidaycheck/auth0-bundler#148]
First of all, I'm very excited when found this project. All this while, I've created and maintained my own bundler for the same purpose

Some of my dependencies are using `flow`. It would be very helpful if I can add `flow` preset to the babel config. And by doing that, I think it worth to allow babel plugins to be extended as well, as people might want to add individual feature that are not part of `preset-env`.

**Comment by selaux** [comment]
Might make sense, could you outline how this should look from a usage standpoint?

Something like:

```
bundler.bundleRule(config, 'my-rule.js', {
    babel: {
         presets: [ 'flow' ],
         plugins: [ 'whatever' ]
    }
})
```

Should those overwrite the existing config then?

**Comment by faizshukri** [comment]
Well, I figured I need to do that on rollup instead. And I did something like [this](https://github.com/learndot/auth0-bundler/commit/1bf65ff89e0f969d714f7a882c4dc30455081e9e).

Later, I can extends the rollup plugin as this.
```js
const createBundler = require("auth0-bundler");
const rollupFlow = require("rollup-plugin-flow");
const rollupCleanup = require("rollup-plugin-cleanup");

const bundler = createBundler({
  nodeVersion: 8,
  plugins: defaultPlugins => [
    rollupFlow(),
    ...defaultPlugins,
    rollupCleanup()
  ]
});
```

**Comment by dplate** [comment]
Its quite obvious, but there are no updates to this project from our side anymore. I close this issue.
