### ISSUE TITLE
In TypeScript, ES6 module imports are undefined when rules are executed

### ISSUE THREAD

**Issue by taras** [holidaycheck/auth0-bundler#200]
👋 Firstly, thank you for sharing this library. It's very helpful to us.

## Our setup

Our rules are in TypeScript. We use Babel to compile TypeScript to JavaScript, then execute the Babel plugin provided by this library to convert JavaScript ES6 modules to rules that Auth0 will accept.

```tsx
BabelPluginExportToFunction(buildLiteralAST(config), {
  commonjs: false,
  nodeVersion: 12,
})
```

## Observed behavior

This was verified with TypeScript 3.3 & 4.4

This setup was working fine as long as we use Node.js `require` syntax. Once we switched to using ES6 modules, we found that modules imported with ES6 syntax evaluate to `undefined` at runtime. This is caused by the AST transform because it produces code where the wrapped function is executed before the transpiled ES6 modules are evaluated.

For example,

```ts
import fetch from 'node-fetch'

export default async function myRule() {
  await fetch('example.com')
}
```

will compile to something that looks roughly like this,

```js
function () {
  myRule();

  var fetch = require('node-fetch');
  
  async function myRule() {
     // fetch here is undefined because when `myRule()` is executed before `var fetch = require('node-fetch');` is evaluated.
     await fetch('example.com')
  }
}
```

## Possible solution

One possible solution is to change the AST transform to add the program execution at the end of the wrapper function.

```diff
function () {
-  myRule();

  var fetch = require('node-fetch');
  
  async function myRule() {
     // fetch here is undefined because when `myRule()` is executed, `var fetch = require('node-fetch');` did not run yet.
     await fetch('example.com')
  }

+ myRule();
}
```

## Current workaround

To get proper TypeScript types in the editor and have working rules, we import types with ES6 modules and use `require` in the body of the rule function.

```ts
import nodeFetch from 'node-fetch'

export default async function myRule() {
  const fetch: typeof NodeFetch = require('node-fetch');

  await fetch('example.com')
}
```

If it'll be helpful, I could create a minimal reproduction for this problem.

**Comment by dplate** [comment]
Its quite obvious, but there are no updates to this project from our side anymore. I close this issue.
