### ISSUE TITLE
Fixate and verify versions of external dependencies

### ISSUE THREAD

**Issue by lo1tuma** [holidaycheck/auth0-bundler#9]
We don’t bundle external dependencies (e.g. `require('request')`), but in order to run local tests against a bundled configuration one would install those dependencies as `devDependencies`.
To make sure we use the same version when running remotely as webtask as we do for running local tests `auth0-bundler` could try to determine the dependency version at build-time and rewrite `require` call from `require('module')` to `require('module@<determined-local-version>')`.
In order to do this reliably we should also verify if the determined version is also available in webtask (https://tehsis.github.io/webtaskio-canirequire/), if not we should let the build fail.

**Comment by fstoerkle** [comment]
In order to check if/what version of a module is available on webtask.io, we can use the [`wt-cli` tool](https://github.com/auth0/wt-cli): e.g `wt modules versions bluebird` yields this ouput:

```
Searching for the versions of bluebird that are already available on the platform...
We found 6 versions for the module: bluebird
3.5.0: available
3.4.7: available
3.4.6: available
2.11.0: available
2.9.26: available
1.2.4: available
```

**Comment by fstoerkle** [comment]
If a specific version we require is not available, we could even add it automatically via `wt modules add ramda@0.22.0 --wait`

**Comment by taras** [comment]
While this is not yet available, I'm using `search-and-replace` babel plugin to replace `@sentry/node` with `@sentry/node@6.2.0` to force Auth0 to use versions specify in peekDependencies.

```
      [
        'search-and-replace',
        {
          rules: Object.entries(pkg.peerDependencies).map(
            ([name, version]) => ({
              search: name,
              replace: `${name}@${version}`,
            })
          ),
        },
      ],
```

**Comment by dplate** [comment]
Its quite obvious, but there are no updates to this project from our side anymore. I close this issue.
